// Mocks generated by Mockito 5.4.6 from annotations
// in projeto_integrador2/test/views/tela_inicial_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:fl_chart/fl_chart.dart' as _i5;
import 'package:flutter/material.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:projeto_integrador2/viewmodels/agenda_viewmodel.dart' as _i2;
import 'package:projeto_integrador2/viewmodels/inicial_viewmodel.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTelaAgendaViewModel_0 extends _i1.SmartFake
    implements _i2.TelaAgendaViewModel {
  _FakeTelaAgendaViewModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InicialViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockInicialViewModel extends _i1.Mock implements _i3.InicialViewModel {
  MockInicialViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TelaAgendaViewModel get agendaViewModel =>
      (super.noSuchMethod(
            Invocation.getter(#agendaViewModel),
            returnValue: _FakeTelaAgendaViewModel_0(
              this,
              Invocation.getter(#agendaViewModel),
            ),
          )
          as _i2.TelaAgendaViewModel);

  @override
  int get selectedIndex =>
      (super.noSuchMethod(Invocation.getter(#selectedIndex), returnValue: 0)
          as int);

  @override
  double get metaAguaDiaria =>
      (super.noSuchMethod(Invocation.getter(#metaAguaDiaria), returnValue: 0.0)
          as double);

  @override
  String get aguaConsumidaFormatada =>
      (super.noSuchMethod(
            Invocation.getter(#aguaConsumidaFormatada),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#aguaConsumidaFormatada),
            ),
          )
          as String);

  @override
  String get metaAguaFormatada =>
      (super.noSuchMethod(
            Invocation.getter(#metaAguaFormatada),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#metaAguaFormatada),
            ),
          )
          as String);

  @override
  double get progressoAgua =>
      (super.noSuchMethod(Invocation.getter(#progressoAgua), returnValue: 0.0)
          as double);

  @override
  double get aguaConsumidaHoje =>
      (super.noSuchMethod(
            Invocation.getter(#aguaConsumidaHoje),
            returnValue: 0.0,
          )
          as double);

  @override
  double get metaRacaoDiaria =>
      (super.noSuchMethod(Invocation.getter(#metaRacaoDiaria), returnValue: 0.0)
          as double);

  @override
  String get racaoConsumidaFormatada =>
      (super.noSuchMethod(
            Invocation.getter(#racaoConsumidaFormatada),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#racaoConsumidaFormatada),
            ),
          )
          as String);

  @override
  String get metaRacaoFormatada =>
      (super.noSuchMethod(
            Invocation.getter(#metaRacaoFormatada),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#metaRacaoFormatada),
            ),
          )
          as String);

  @override
  double get progressoRacao =>
      (super.noSuchMethod(Invocation.getter(#progressoRacao), returnValue: 0.0)
          as double);

  @override
  double get racaoConsumidaHoje =>
      (super.noSuchMethod(
            Invocation.getter(#racaoConsumidaHoje),
            returnValue: 0.0,
          )
          as double);

  @override
  String get proximaRefeicao =>
      (super.noSuchMethod(
            Invocation.getter(#proximaRefeicao),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#proximaRefeicao),
            ),
          )
          as String);

  @override
  String get tempoAteProximaRefeicao =>
      (super.noSuchMethod(
            Invocation.getter(#tempoAteProximaRefeicao),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#tempoAteProximaRefeicao),
            ),
          )
          as String);

  @override
  List<_i5.FlSpot> get consumoSemanalSpots =>
      (super.noSuchMethod(
            Invocation.getter(#consumoSemanalSpots),
            returnValue: <_i5.FlSpot>[],
          )
          as List<_i5.FlSpot>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> atualizarRacaoConsumida(double? novoValor) =>
      (super.noSuchMethod(
            Invocation.method(#atualizarRacaoConsumida, [novoValor]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> atualizarAguaConsumida(double? novoValor) =>
      (super.noSuchMethod(
            Invocation.method(#atualizarAguaConsumida, [novoValor]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onItemTapped(int? index, _i7.BuildContext? context) =>
      super.noSuchMethod(
        Invocation.method(#onItemTapped, [index, context]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
