// Mocks generated by Mockito 5.4.6 from annotations
// in projeto_integrador2/test/viewmodels/inicial_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i5;

import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:projeto_integrador2/viewmodels/agenda_viewmodel.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TelaAgendaViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTelaAgendaViewModel extends _i1.Mock
    implements _i2.TelaAgendaViewModel {
  MockTelaAgendaViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.RefeicaoProgramada> get perfilHorarios =>
      (super.noSuchMethod(
            Invocation.getter(#perfilHorarios),
            returnValue: <_i2.RefeicaoProgramada>[],
          )
          as List<_i2.RefeicaoProgramada>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> carregarPerfil() =>
      (super.noSuchMethod(
            Invocation.method(#carregarPerfil, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> salvarPerfil() =>
      (super.noSuchMethod(
            Invocation.method(#salvarPerfil, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void adicionarNovaRefeicao() => super.noSuchMethod(
    Invocation.method(#adicionarNovaRefeicao, []),
    returnValueForMissingStub: null,
  );

  @override
  void removerRefeicaoDefinitivamente(int? index) => super.noSuchMethod(
    Invocation.method(#removerRefeicaoDefinitivamente, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void atualizarHorarioRefeicao(int? index, _i4.TimeOfDay? novoHorario) =>
      super.noSuchMethod(
        Invocation.method(#atualizarHorarioRefeicao, [index, novoHorario]),
        returnValueForMissingStub: null,
      );

  @override
  void atualizarQuantidadeRacaoRefeicao(int? index, String? novaQuantidade) =>
      super.noSuchMethod(
        Invocation.method(#atualizarQuantidadeRacaoRefeicao, [
          index,
          novaQuantidade,
        ]),
        returnValueForMissingStub: null,
      );

  @override
  void atualizarQuantidadeAguaRefeicao(int? index, String? novaQuantidade) =>
      super.noSuchMethod(
        Invocation.method(#atualizarQuantidadeAguaRefeicao, [
          index,
          novaQuantidade,
        ]),
        returnValueForMissingStub: null,
      );

  @override
  void toggleAtivacaoRefeicao(int? index) => super.noSuchMethod(
    Invocation.method(#toggleAtivacaoRefeicao, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
